In [1]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf
import keras

C:\ProgramData\anaconda3\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

In [3]:
df=pd.read_csv(r"C:\Users\Administrator\Desktop\top_companies_20y_daily_combined.csv")
df.head()

,Date,Ticker,Open,High,Low,Close,Adj Close,Volume
0,2006-01-02,000660.KS,36100.0,37650.0,35850.0,37600.0,27358.396484,13334311.0
1,2006-01-03,000660.KS,38100.0,38400.0,36850.0,38200.0,27794.970703,13815168.0
2,2006-01-04,000660.KS,38250.0,39050.0,35300.0,35400.0,25757.650391,23064896.0
3,2006-01-05,000660.KS,35900.0,36000.0,33600.0,34750.0,25284.687500,21043236.0
4,2006-01-06,000660.KS,34950.0,35850.0,34850.0,35100.0,25539.355469,12557226.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230111 entries, 0 to 230110
Data columns (total 8 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Date       230111 non-null  object
 1   Ticker     230111 non-null  object
 2   Open       230111 non-null  float64
 3   High       230111 non-null  float64
 4   Low        230111 non-null  float64
 5   Close      230111 non-null  float64
 6   Adj Close  230111 non-null  float64
 7   Volume     230111 non-null  float64
dtypes: float64(6), object(2)
memory usage: 14.0+ MB

In [16]:
df['Date'] = df['Date'].astype('int64')  # nanoseconds

In [23]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Ticker'] = le.fit_transform(df['Ticker'])

In [24]:
df['Volume'] = df['Volume'].astype('int64')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230111 entries, 0 to 230110
Data columns (total 8 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Date       230111 non-null  int64
 1   Ticker     230111 non-null  int64
 2   Open       230111 non-null  float64
 3   High       230111 non-null  float64
 4   Low        230111 non-null  float64
 5   Close      230111 non-null  float64
 6   Adj Close  230111 non-null  float64
 7   Volume     230111 non-null  int64
dtypes: float64(5), int64(3)
memory usage: 14.0 MB

In [26]:
df.isnull().sum()

Date         0
Ticker       0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [27]:
X=df.drop(columns='Volume')
y=df['Volume']

In [32]:
X

,Date,Ticker,Open,High,Low,Close,Adj Close
0,1136160000000000000,0,36100.000000,37650.000000,35850.000000,37600.000000,27358.396484
1,1136246400000000000,0,38100.000000,38400.000000,36850.000000,38200.000000,27794.970703
2,1136332800000000000,0,38250.000000,39050.000000,35300.000000,35400.000000,25757.650391
3,1136419200000000000,0,35900.000000,36000.000000,33600.000000,34750.000000,25284.687500
4,1136505600000000000,0,34950.000000,35850.000000,34850.000000,35100.000000,25539.355469
...,...,...,...,...,...,...,...
230106,1770940800000000000,48,150.550003,151.660004,147.979996,148.449997,148.449997
230107,1771286400000000000,48,148.199997,149.130005,145.149994,146.190002,146.190002
230108,1771372800000000000,48,148.149994,150.979996,147.610001,150.679993,150.679993
230109,1771459200000000000,48,152.199997,153.380005,150.839996,150.970001,150.970001
230110,1771545600000000000,48,150.490005,150.809998,146.460007,147.279999,147.279999

In [28]:
## spliting dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [29]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [31]:
from keras.models import Sequential
from keras.layers import Dense

In [33]:
def ann_model_regressor():
    
    ### initializing the ANN
    model=Sequential()
    
    ###adding input layer and first hidden layer
    model.add(Dense(input_dim=7, units=8, activation='relu',kernel_initializer="uniform"))
    
    ### adding second layer
    model.add(Dense(units=8, activation='relu',kernel_initializer="uniform"))
    
    ### adding output layer
    model.add(dense(units=1,activation='relu',kernel_initializer="uniform"))
    
    ### compiling the ANN
    model.compile(optimizer = 'adam', loss = 'mean_squared_error')
    return model

In [34]:
def ann_model_regressor():
    model=Sequential()
    model.add(Dense(input_dim=7, units=8, activation='relu',kernel_initializer="uniform"))
    model.add(Dense(units=8, activation='relu',kernel_initializer="uniform"))
    model.add(Dense(units=1,activation='relu',kernel_initializer="uniform"))
    model.compile(optimizer = 'adam', loss = 'mean_squared_error')
    return model

In [35]:
ann = ann_model_regressor()

C:\ProgramData\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [36]:
### training the ANN model on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step - loss: 26050555050721280.0000
Epoch 2/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step - loss: 26041477637341184.0000
Epoch 3/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - loss: 26016833114996736.0000
Epoch 4/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step - loss: 25971048763621376.0000
Epoch 5/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step - loss: 25898519650893824.0000
Epoch 6/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step - loss: 25795165557882880.0000
Epoch 7/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - loss: 25658592040321024.0000
Epoch 8/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 25481789711581184.0000
Epoch 9/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 25268701351641088.0000
Epoch 10/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - loss: 25016765012508672.0000
Epoch 11/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - loss: 24733576343846912.0000
Epoch 12/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - loss: 24414226198036480.0000
Epoch 13/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - loss: 24078492899475456.0000
Epoch 14/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - loss: 23732086607183872.0000
Epoch 15/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step - loss: 23388265885204480.0000
Epoch 16/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - loss: 23058792501477376.0000
Epoch 17/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 22752703067193344.0000
Epoch 18/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step - loss: 22486062907523072.0000
Epoch 19/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step - loss: 22273562958102528.0000
Epoch 20/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - loss: 22107860972339200.0000
Epoch 21/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step - loss: 21985222476169216.0000
Epoch 22/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 21904960274825216.0000
Epoch 23/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step - loss: 21853126462013440.0000
Epoch 24/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 21819058781421568.0000
Epoch 25/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - loss: 21797178070532096.0000
Epoch 26/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - loss: 21783904474103808.0000
Epoch 27/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step - loss: 21774715391574016.0000
Epoch 28/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 21768670225104896.0000
Epoch 29/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step - loss: 21763829796962304.0000
Epoch 30/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 21760417445445632.0000
Epoch 31/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 33s 4ms/step - loss: 21757595651932160.0000
Epoch 32/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 41s 4ms/step - loss: 21755136783155200.0000
Epoch 33/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 53s 6ms/step - loss: 21753092378722304.0000
Epoch 34/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 32s 4ms/step - loss: 21751318557229056.0000
Epoch 35/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 41s 4ms/step - loss: 21749654257401856.0000
Epoch 36/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 38s 4ms/step - loss: 21748206853423104.0000
Epoch 37/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 21746879708528640.0000
Epoch 38/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 21745681412653056.0000
Epoch 39/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - loss: 21744592638443520.0000
Epoch 40/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 21743609090932736.0000
Epoch 41/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - loss: 21742670640578560.0000
Epoch 42/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 21741884661563392.0000
Epoch 43/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - loss: 21741111567450112.0000
Epoch 44/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step - loss: 21740465174872064.0000
Epoch 45/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - loss: 21739861731966976.0000
Epoch 46/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step - loss: 21739266878996480.0000
Epoch 47/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step - loss: 21738779400208384.0000
Epoch 48/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - loss: 21738287626452992.0000
Epoch 49/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - loss: 21737881752043520.0000
Epoch 50/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 21737462992732160.0000
Epoch 51/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - loss: 21737147312635904.0000
Epoch 52/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step - loss: 21736795125317632.0000
Epoch 53/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step - loss: 21736399988326400.0000
Epoch 54/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 21736140142804992.0000
Epoch 55/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 21735852379996160.0000
Epoch 56/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step - loss: 21735551732285440.0000
Epoch 57/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - loss: 21735296181731328.0000
Epoch 58/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 21735044926144512.0000
Epoch 59/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step - loss: 21734793670557696.0000
Epoch 60/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 21734551004905472.0000
Epoch 61/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 21734284716933120.0000
Epoch 62/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 21734108623273984.0000
Epoch 63/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step - loss: 21733928234647552.0000
Epoch 64/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 21733782205759488.0000
Epoch 65/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 21733537392623616.0000
Epoch 66/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step - loss: 21733288284520448.0000
Epoch 67/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - loss: 21733165877952512.0000
Epoch 68/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 21733058503770112.0000
Epoch 69/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 21732878115143680.0000
Epoch 70/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 21732710611419136.0000
Epoch 71/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - loss: 21732596794785792.0000
Epoch 72/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 21732498010537984.0000
Epoch 73/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 21732343391715328.0000
Epoch 74/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 21732244607467520.0000
Epoch 75/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 21732102873546752.0000
Epoch 76/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step - loss: 21731958992142336.0000
Epoch 77/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step - loss: 21731825848156160.0000
Epoch 78/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step - loss: 21731757128679424.0000
Epoch 79/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - loss: 21731604657340416.0000
Epoch 80/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - loss: 21731477955805184.0000
Epoch 81/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 21731402793877504.0000
Epoch 82/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - loss: 21731304009629696.0000
Epoch 83/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 43s 4ms/step - loss: 21731220257767424.0000
Epoch 84/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 40s 4ms/step - loss: 21731080671330304.0000
Epoch 85/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - loss: 21731014099337216.0000
Epoch 86/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 44s 4ms/step - loss: 21730885250318336.0000
Epoch 87/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 39s 4ms/step - loss: 21730790761037824.0000
Epoch 88/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 44s 5ms/step - loss: 21730696271757312.0000
Epoch 89/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - loss: 21730563127771136.0000
Epoch 90/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 43s 4ms/step - loss: 21730414951399424.0000
Epoch 91/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - loss: 21730361264308224.0000
Epoch 92/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 43s 5ms/step - loss: 21730241005223936.0000
Epoch 93/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - loss: 21730146515943424.0000
Epoch 94/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - loss: 21730082091433984.0000
Epoch 95/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 26s 5ms/step - loss: 21730011224473600.0000
Epoch 96/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - loss: 21729848015716352.0000
Epoch 97/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 41s 4ms/step - loss: 21729775001272320.0000
Epoch 98/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 44s 5ms/step - loss: 21729628972384256.0000
Epoch 99/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 40s 5ms/step - loss: 21729562400391168.0000
Epoch 100/100
5753/5753 ━━━━━━━━━━━━━━━━━━━━ 41s 4ms/step - loss: 21729455026208768.0000

In [37]:
### Predicting the results
ypred_train = ann.predict(X_train)
ypred_test = ann.predict(X_test)

5753/5753 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step
1439/1439 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step

In [38]:
from sklearn.metrics import mean_squared_error
print("MSE for train data: ",mean_squared_error(y_train,ypred_train))
print("MSE for test data: ", mean_squared_error(y_test,ypred_test))

MSE for train data:  2.1729317587255296e+16
MSE for test data:  1.852790050442445e+16

In [39]:
from sklearn.metrics import r2_score
print("R2 for train data: ",r2_score(y_train,ypred_train))
print("R2 for train data: ",r2_score(y_test,ypred_test))

R2 for train data:  0.045644283294677734
R2 for train data:  0.05389070510864258